### PR TITLE
Handle the runtime deps.

### PR DESCRIPTION
**Pull request by leamas**
Handle the libgeotiff dependency, and the implicit proj pulled in by libgeotiff.

On most platforms done by rebuilding from source. Windows is using pre-compiled binaries since long. Rpi-armhf  are handled by rebuilt debian packages with usable static libs (rebuilding deps form source takes hours in the builders, it jus't don't work)

The obvious solution to use the static libraries available in the Debian -dev packages is tried but doesn't work since the libs are compiled without -fPIC. We should approach Debian on this, if they changed the compilation flags we would have a more stable solution.  That said, the current setup should be robust besides the rpi stuff which will need to be rebuilt for upcoming Debian/raspbian versions.

EDIT: The dependency info is duplicated in the flatpak yaml manifest and the build-deps/ files. It is possible to get around this by letting flatpak build it's deps in the main flatpak module. This is tested and works. However, it breaks the caching which makes flatpak need around 10 minutes for each build. I have concluded that the duplicated config info is a less evil than the otherwise excessive build times.

The long compilation times for the dependencies has made it necessary to add caching to the Debian builds (other platforms are already cached).

This is a large PR, and we might need some time after merging this before the dust settles. It contains solution which should be able to apply when other plugins runs into similar troubles.

Closes: #22

### CODE REVIEW

**Comment by leamas** [comment]
Oops, I have been so búsy with all linuxes and Macs, I forgot Windows. Please don't merge until appveyor is fixed.

**Comment by leamas** [comment]
I need some more time. The patch works, but it needs polish. But I don't have more time now. Let us just let it sit here for a while.

**Comment by leamas** [comment]
Fixed windows (multiple bugs & overall mess), some more polish. Ready to merge from my side.

**Comment by Rasbats** [comment]
Does libglu1-mesa-dev need adding to control-raspbian?

[https://www.cruisersforum.com/forums/showthread.php?p=3319962#post3319962](url)

Had to reinstate wxImageHandler for the Mac, which I removed by mistake. At the moment there is an issue with the wxMenu not showing on the Mac. This also affects Weatherfax (on which Photolayer is based).

**Comment by leamas** [comment]
Post mentions libgeotiff-dev, libjsoncpp-dev and libglu1-mesa-dev.

   - libgeotiff-dev should be fixed by my last PR
   - libjsoncpp:  We bundle that one, so a runtime dependency on this is a bug, most likely simple.
   - libglu1-mesa-dev: this is is basically libGLU.so, with the correspondig headers glu.h and glu_magle.h. I can see the dependency, but a simple search for glu.h doesn't return anything. An indirect dep? We need to fid out the root of this dependency.
   
> Had to reinstate wxImageHandler for the Mac, which I removed by mistake

Don't follow you here. Could you please expand a little?

**Comment by leamas** [comment]
jsoncpp is probably fixed by this, untested patch:

```
diff --git a/libs/jsoncpp/CMakeLists.txt b/libs/jsoncpp/CMakeLists.txt
index a10a377..5a2fbdc 100644
--- a/libs/jsoncpp/CMakeLists.txt
+++ b/libs/jsoncpp/CMakeLists.txt
@@ -5,7 +5,7 @@ endif ()
 cmake_minimum_required(VERSION 3.1.0)
 project("jsoncpp")
 
-option(USE_SYSTEM_JSONCPP "Use system copy of library if available" ON)
+option(USE_SYSTEM_JSONCPP "Use system copy of library if available" OFF)

```

**Comment by leamas** [comment]
It looks like libGLU is pulled in  by core wxWidgets, see for example https://packages.debian.org/stretch/libwxgtk3.0-dev.

Also, this seems like a platform problem. The regular Debian builds creates a library not linked to  libGLU. Likewise for main opencpn. This means that unless there is some very specialized code form arm, which we doubt, the dependency is bogus. The question still is what causes it.

Confused, but running out of time for now... 

Bringing issue upstream: https://github.com/OpenCPN/OpenCPN/issues/2149

**Comment by Rasbats** [comment]
>Had to reinstate wxImageHandler for the Mac, which I removed by mistake

I was aligning photolayer with old files. The panel icon is .png. For the Mac it is necessary to use this code or the plugin will not load on the Mac.

      `wxInitAllImageHandlers();

    wxLogDebug(wxString("Using icon path: ") + path);
    if (!wxImage::CanRead(path)) {
        wxLogDebug("Initiating image handlers.");
        wxInitAllImageHandlers();
    }
    wxImage panelIcon(path);
    if (panelIcon.IsOk())
        m_panelBitmap = wxBitmap(panelIcon);
    else
        wxLogWarning("Photolayer panel icon has NOT been loaded");`

**Comment by Rasbats** [comment]
Having problems with your patch for jsoncpp/CMakeLists.txt. Getting corrupt patch when I make the .patch file. Line endings? I will do it by hand.

**Comment by leamas** [comment]
>  will do it by hand.

Well, isn't that a typical patch to apply by hand ;)

>  Mac it is necessary to use this code or the plugin will not load on the Mac.

Ah... memories from when I struggled w main opencpn. Even if it's only required on Mac, it should make it more robust on all platforms.

**Comment by Rasbats** [comment]
Making the .patch file was an attempt to learn more about patches. Now back to the menubar and making it appear in the Mac.

**Comment by Rasbats** [comment]
Problem with the Mac build:

[https://app.circleci.com/pipelines/github/Rasbats/photolayer_pi/311/workflows/796790a9-27bc-4869-9672-bfff398a3b1c/jobs/3133](url)

Have now reverted this commit to allow me to work on the menu problem.

**Pull request merged**
