### PR TITLE
Opengl - Drop the abomination 

### PR DESCRIPTION
**Pull request by leamas**
Drop some really bad code used when locating and linking to OpenGL libs.

Since the OpenGL libs are located already in PluginLibs, and these libs are also generally useful, augment the code in PluginLibs to not only locate but also link. And drop the SetupOpenGL abomiination.,

This means changes in the cmake/ directory. I will follow up with a PT to shipdriver so these changes are reflected also in the reference  plugin.  I don't see they should be problematic in other plugins.

### CODE REVIEW

**Comment by Rasbats** [comment]
Saw you had been busy last night! I tried  a local build from your 'build' branch. It makes the tarball without any errors but when I install it there is a crash of OpenCPN. From the log:

`08:13:16.757 MESSAGE pluginmanager.cpp:2232 PlugInManager: Loading PlugIn: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib
08:13:16.767   ERROR dlunix.cpp:162 dlopen(/Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib, 2): Symbol not found: _proj_context_create
  Referenced from: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib
  Expected in: flat namespace
 in /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib
08:13:16.767 MESSAGE pluginmanager.cpp:2291    PlugInManager: Cannot load library: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib 
`
Is there something needs a fix?

**Comment by Rasbats** [comment]
The 'include' folder has gone but PhotoLayerImage.cpp still has the include 'gl.h'. Is this available elsewhere?

**Comment by leamas** [comment]
> Is there something needing a fix?

Obviously, yes.

**Comment by leamas** [comment]
>  Symbol not found: _proj_context_create

This is on macos. Have you similar problems on Windows? flatpak looks ok...

**Comment by Rasbats** [comment]
Windows is working correctly.

**Comment by leamas** [comment]
I can reproduce, sort of, but the log is different, it doesn't find the wxWidgets libraries. The net result seem to be that the runtime loader doesn't see what it should see. Have a small window now, otherwise late today.

**Comment by Rasbats** [comment]
I am looking at this. About to have a play.

[https://github.com/Kortforsyningen/PROJ-JNI/issues/24](https://github.com/Kortforsyningen/PROJ-JNI/issues/24)

Includes osgeo stuff.

**Comment by leamas** [comment]
I might have clue, at last on my box. Could you please try doing `sudo cp  /tmp/wx312B_opencpn50_macos109/lib/*stc* /Applications/OpenCPN.app/Contents/Frameworks` and then test again (on macos, that is)

**Comment by Rasbats** [comment]
Stil the same error:

`14:39:25.667 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib
14:39:25.668 MESSAGE pluginmanager.cpp:2169 Plugin is compatible: true

14:39:25.668 MESSAGE pluginmanager.cpp:2232 PlugInManager: Loading PlugIn: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib

14:39:25.672   ERROR dlunix.cpp:162 dlopen(/Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib, 2): Symbol not found: _proj_context_create
  Referenced from: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib  Expected in: flat namespace
 in /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib

14:39:25.672 MESSAGE pluginmanager.cpp:2291    PlugInManager: Cannot load library: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib `

I am going to take your build code and try again, just in case.

**Comment by Rasbats** [comment]
No... the same result.

When working on Javascript_pi I needed stc and compiled my own wxWidgets-3.1.2, including stc. Have I created a problem for myself again!

**Comment by Rasbats** [comment]
When installing I get the jigsaw icon for the plugin. When reinstalling the photolayer line disappears. Found again in the list of plugins available.

**Comment by leamas** [comment]
I can reproduce your error. That's a start. Obviously, this means that we miss some library. 

I'm on it.

**Comment by Rasbats** [comment]
Took the code from your 'build' branch.
Still the error:

`18:08:31.661 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib

18:08:31.661 MESSAGE pluginmanager.cpp:2169 Plugin is compatible: true

18:08:31.661 MESSAGE pluginmanager.cpp:2232 PlugInManager: Loading PlugIn: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib

18:08:31.712   ERROR dlunix.cpp:162 dlopen(/Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib, 2): Symbol not found: _proj_context_create
  Referenced from: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib  Expected in: flat namespace
 in /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib

18:08:31.712 MESSAGE pluginmanager.cpp:2291    PlugInManager: Cannot load library: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib 
`
Does the source code need to link with 'proj.h' and do I need 'proj_context_create()' in the code? Things for me to try.

**Comment by leamas** [comment]
The problem is that we are not linking to the proj library on MacOS. It isn't solved, but under way (doing other things in between).

**Comment by leamas** [comment]
@rasbats: I think I know what's going on. But running out of time now. Back later

PS: Good catch, this. Thanks!

**Comment by leamas** [comment]
OK, I think that's it. Here was actually two bugs. One was about https://github.com/OpenCPN/OpenCPN/issues/2153, handled by avoiding to link to unused wxWidgets packages like stc.

The other was kind of weird. Although the proj library was built for macos, it wasn't linked. Sigh. 

Thanks for testing my silly mistakes :))

**Comment by Rasbats** [comment]
Here goes : , ) I wwill look at the output in the morning!

**Comment by leamas** [comment]
Circle ci build logs [here](https://app.circleci.com/pipelines/github/leamas/photolayer_pi/187/workflows/ba2f057d-b2b1-4b4b-923c-59433593fd35)

**Comment by leamas** [comment]
> When working on Javascript_pi I needed stc and compiled my own wxWidgets-3.1.2, including stc. Have I created a problem for myself again!

Yes. That version will not be available for the user in runtime. The macOS wxwidgets runtime lives in  `/Applications/OpenCPN.app/Contents/Frameworks, `and doesn't contain the stc lib. See https://github.com/OpenCPN/OpenCPN/issues/2153.

I would appreciate if we could keep this discussion here, leaving the 2153 for the more general question.

**Comment by Rasbats** [comment]
We still have a problem with linking proj. This was using your 'build' branch and compiling locally, but I had the same issue with one from my Cloudsmith.

`10:39:42.363 MESSAGE pluginmanager.cpp:1167 Found 1 candidates

10:39:42.363 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib

10:39:42.363 MESSAGE pluginmanager.cpp:2169 Plugin is compatible: true

10:39:42.363 MESSAGE pluginmanager.cpp:2232 PlugInManager: Loading PlugIn: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib

10:39:42.411   ERROR dlunix.cpp:162 dlopen(/Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib, 2): Symbol not found: _proj_context_create  Referenced from: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib  Expected in: flat namespace in /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib

10:39:42.411 MESSAGE pluginmanager.cpp:2291    PlugInManager: Cannot load library: /Users/mikerossiter/Library/Application Support/OpenCPN/Contents/PlugIns/libphotolayer_pi.dylib 
`

**Comment by Rasbats** [comment]
- Installs and runs on Windows
- No crashes on the Mac, although the jigsaw icon is used and the plugin fails

**Comment by leamas** [comment]
The branch to build is the opengl branch, the one in this PR as obvious form top of this page.

I'm building it locally on my Big Sur VM, and it works fine. 

In particular, you can check the plugin using the nm command, something like  `nm app/photolayer-3.3-darwin-10.13.6/OpenCPN.app/Contents/PlugIns/libphotolayer_pi.dylib  | grep _proj`. For me, this gives (excerpt):

```
00000000002359c0 T __Z26pj_get_relative_share_projP9projCtx_t
00000000001aa850 T _proj_alter_id
00000000001aa5f0 T _proj_alter_name
000000000021e270 T _proj_angular_input
000000000021e2a0 T _proj_angular_output
0000000000220290 T _proj_area_create
00000000002202d0 T _proj_area_destroy
00000000002202b0 T _proj_area_set_bbox
00000000001a2310 T _proj_as_proj_string
00000000001a2790 T _proj_as_projjson
00000000001a1e60 T _proj_as_wkt
0000000000210e20 T _proj_assign_context
000000000020f860 T _proj_cleanup
000000000019d600 T _proj_clone

```

If the linkage fails (which it seems to have done for you), there is an U instead of a T following the address.

**Comment by leamas** [comment]
One thing... If you have the libgeotiff library installed using brew, the build will link to it if using the cmake parameters in circleci-build-macos.  It's about the  -DUSE_SYSTEM_GEOTIFF:BOOL="ON"  line.  It does the right thing in the builder, because here the system copy is the cached one. But it 's wrong on your local build if libgeotiff is installed there. Either remove the brew libgeotiff package in /usr/local (and the same for proj). Or change to DUSE_SYSTEM_GEOTIFF:BOOL=OFF.

**Comment by Rasbats** [comment]
Whoopee F... The local build worked, with your DUSE_SYSTEM_GEOTIFF:BOOL=OFF. Now I am going to grab your code and get it into my Cloudsmith.

**Comment by Rasbats** [comment]
Something is going wrong with my Circleci build for the Mac. My own installer, DUSE_SYSTEM_GEOTIFF:BOOL=OFF, works perfectly but the Circleci one built with DUSE_SYSTEM_GEOTIFF:BOOL=ON does not.

armhf-stretch and armhf-buster fail with the pip upgrade:

```
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-21.0
+ python3 -m pip install --user cloudsmith-cli
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

Exited with code exit status 1
```

**Comment by leamas** [comment]
That's the bad python pip release 21.0.0. Cherry-pick the last commit from shipdriver, it solves it.

**Comment by Rasbats** [comment]
Will do.

**Comment by Rasbats** [comment]
I will test the dylib with nm to see whether proj is linked in. A walk first.

**Comment by Rasbats** [comment]
Finally got my photolayer_pi github resembling yours. .gitignore stopped me adding some stuff. Duh....

Various issues remain:

1. The builder builds seem to run for MacOS but the tarball does not work. Proj error again.

```
CMakeFiles/photolayer_pi.dir/src/icons.cpp.o -c
/Users/mikerossiter/Documents/github/photolayer_pi-8dab/src/icons.cpp make[6]: *** No rule to make target `_proj_implib-NOTFOUND', needed by `libphotolayer_pi.dylib'. Stop.
make[6]: *** Waiting for unfinished jobs....
[ 98%] Building CXX object CMakeFiles/photolayer_pi.dir/src/wximgkap.cpp.
```

[photolayer.pdf](https://github.com/Rasbats/photolayer_pi/files/5873284/photolayer.pdf)

On  the Mac when I try to build PhotoLayer locally with DUSE_SYSTEM_GEOTIFF:BOOL=ON with libgeotiff and proj removed the build fails. With libgeotiff and proj installed again and DUSE_SYSTEM_GEOTIFF:BOOL=OFF the local build works again.

-  With ci/circleci-build-macos.sh edited to use DUSE_SYSTEM_GEOTIFF:BOOL=OFF on my github the Circleci builder makes a good tarball. It seems that USE_SYSTEM_GEOTIFF:BOOL=ON is not working for the builder.
-  Tried a tarball from your Cloudsmith and that also failed, even though it seemed to have built correctly on Circleci.
-  Is there a quicker way of building?... it takes a long time compiling libgeotiff and proj.

2. The Circleci debian based builds fail with a new error:

```
-- Found wxWidgets: -L/usr/lib/x86_64-linux-gnu;-pthread;;;-lwx_baseu-3.0;-lwx_gtk2u_core-3.0;-lwx_baseu_net-3.0;-lwx_baseu_xml-3.0;-lwx_gtk2u_html-3.0 (found version "3.0.2") 
-- Using bundled jsoncpp.
-- Using system tinyxml
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.6") 
-- Could NOT find GeoTIFF (missing:  GEOTIFF_LIBRARY GEOTIFF_INCLUDE_DIR) 
CMake Error at libs/libgeotiff/Proj.cmake:48 (string):
  string does not recognize sub-command PREPEND
Call Stack (most recent call first):
  libs/libgeotiff/CMakeLists.txt:33 (include) 

```
Windows still ok!

**Comment by Rasbats** [comment]
Sorry... ref 2. It is just the xenial build that failed. The others eventually built ok. Trying a rebuild of this one.

**Comment by Rasbats** [comment]
Just found the same we are using version 3.5.1 minimum. v3.12 added prepend.

**Comment by leamas** [comment]
Seems that PREPEND was added in cmake 3.10. BTW: please always link to the complete build log when there are errors (an excerpt is of course still useful.)

**Comment by Rasbats** [comment]
Updating to v3.10 and doing some more tests.

**Comment by leamas** [comment]
It would be easy to patch, avoiding using prepend. But the correct solution is to handle basic issue with outdated cmake versions. 
> Updating to v3.10 and doing some more tests.

Not that useful since xenial indeed is on 3.5.1. (how has this ever worked for me).

I have bits and pieces in place. I suggest that we for now just lives with the fact that xenial doesn't build. I will make a PR later for the cmake parts.

If it's critical,  this patch (untested) should fix it: 
```
diff --git a/libs/libgeotiff/Proj.cmake b/libs/libgeotiff/Proj.cmake
index 1637339..31e3d99 100644
--- a/libs/libgeotiff/Proj.cmake
+++ b/libs/libgeotiff/Proj.cmake
@@ -45,7 +45,11 @@ ExternalProject_Add(
 set(_proj_obj_path
   ${CMAKE_STATIC_LIBRARY_PREFIX}proj${CMAKE_STATIC_LIBRARY_SUFFIX}
 )
-string(PREPEND _proj_obj_path ${PROJECT_SOURCE_DIR}/proj-*/src/.libs/)
+if (${CMAKE_MAJOR_VERSION} LESS 3 OR ${CMAKE_MINOR_VERSION} LESS 10)
+  set(_proj_obj_path ${PROJECT_SOURCE_DIR}/proj-*/src/.libs/${_proj_obj_path})
+else ()
+  string(PREPEND _proj_obj_path ${PROJECT_SOURCE_DIR}/proj-*/src/.libs/)
+endif ()


```

**Comment by Rasbats** [comment]
> Not that useful since xenial indeed is on 3.5.1.

Yes, It was a wasted build. 

I will add your patch. 

You probably saw that your 9da2dc5 on Cloudsmith does not install on Catalina.

**Comment by Rasbats** [comment]
Second thoughts. I will wait for the work on cmake.

**Comment by leamas** [comment]
regarding [stc](https://github.com/Rasbats/photolayer_pi/pull/28#issuecomment-766454700)

> When working on Javascript_pi I needed stc and compiled my own wxWidgets-3.1.2, including stc. Have I created a problem for myself again!

This is now resolved in main OpenCPN in a [recent PR](https://github.com/OpenCPN/OpenCPN/pull/2156). This  means that your plugin will work for macos users after next OpenCPN release.

While testing, you could copy relevant libraries from the development bundle the installation area:

    cp /tmp/wx312B_opencpn50_macos109/lib/*stc* /Applications/OpenCPN.app/Contents/Frameworks/

This will create the same situation as after next release

**Comment by Rasbats** [comment]
Thanks for the PR for OpenCPN.

**Pull request merged**
